#!/bin/bash

if command -v steam-controller-dsu &>/dev/null; then
    steam-controller-dsu &> "$HOME/steam-controller-dsu.log" &
    scdsu_pid=$!
    echo "steam-controller-dsu running as PID $scdsu_pid"
fi

trap '[ -n "$scdsu_pid" ] && kill "$scdsu_pid"' EXIT

# Prefer X11
export PROTON_ENABLE_WAYLAND=0
export QT_QPA_PLATFORM=xcb

STEAM_CMD="steam -gamepadui"

gamescope \
  -e \
  -g \
  --expose-wayland \
  --force-grab-cursor \
  "$@" \
  -- bash -c "$STEAM_CMD" > "$HOME/gamescope-session.log" 2>&1
