#!/bin/bash
pgrep pipewire | xargs kill 2>/dev/null

pipewire > /dev/null 2>&1 &

for arg in "$@"; do
  case "$arg" in
    --hdr-*)
      export PROTON_ENABLE_HDR=1
      break
      ;;
  esac
done

if command -v steam-controller-dsu &>/dev/null; then
    steam-controller-dsu &> "$HOME/steam-controller-dsu.log" &
    scdsu_pid=$!
    echo "Running as PID $scdsu_pid"
fi

trap '[ -n "$scdsu_pid" ] && kill "$scdsu_pid"' EXIT

# Performance
export MESA_VK_WSI_PRESENT_MODE=mailbox
export STEAM_MULTIPLE_XWAYLANDS=1
export QT_QPA_PLATFORM=xcb

STEAM_CMD="steam -gamepadui"

dbus-run-session gamescope \
  -e \
  --backend drm \
  --adaptive-sync \
  --hide-cursor-delay 99999 \
  --xwayland-count 2 \
  "$@" \
  -- bash -c "$STEAM_CMD" > "$HOME/gamescope-session.log" 2>&1

pgrep pipewire | xargs kill 2>/dev/null
